"""empty message

Revision ID: 7158a0255790
Revises: f62b2cdc2141
Create Date: 2022-03-24 06:42:00.602700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7158a0255790'
down_revision = 'f62b2cdc2141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'price')
    # ### end Alembic commands ###
