"""empty message

Revision ID: 8452b9a799c1
Revises: 7158a0255790
Create Date: 2022-03-24 07:07:24.276803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8452b9a799c1'
down_revision = '7158a0255790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('translate_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'translate_title')
    # ### end Alembic commands ###
