"""empty message

Revision ID: f62b2cdc2141
Revises: afbb8a532271
Create Date: 2022-03-24 06:39:10.732183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f62b2cdc2141'
down_revision = 'afbb8a532271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'price')
    # ### end Alembic commands ###
